server:
  port: 8081

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

minio:
  endpoint: http://阿里云公网ip地址:9000/
  accessKey: root
  secretKey: root123456
  bucketName: ceshi-1


